        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 16 12:09:22 2010
        MODULE LATTICE_COMPUTE_DIFFERENT_REMOVEATOMS__genmod
          INTERFACE 
            SUBROUTINE LATTICE_COMPUTE_DIFFERENT_REMOVEATOMS(NSIA,      &
     &NSITE_OCTA,INDX,LIST_NO_ORDER,NDATOMS)
              INTEGER(KIND=4) :: NSIA
              INTEGER(KIND=4) :: NSITE_OCTA(10,NSIA)
              INTEGER(KIND=4) :: INDX(10*NSIA)
              REAL(KIND=8) :: LIST_NO_ORDER(10*NSIA)
              INTEGER(KIND=4) :: NDATOMS
            END SUBROUTINE LATTICE_COMPUTE_DIFFERENT_REMOVEATOMS
          END INTERFACE 
        END MODULE LATTICE_COMPUTE_DIFFERENT_REMOVEATOMS__genmod
