        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 16 12:09:22 2010
        MODULE LATTICE_COMPUTE_ATOMS_TO_REMOVE__genmod
          INTERFACE 
            SUBROUTINE LATTICE_COMPUTE_ATOMS_TO_REMOVE(ATOMS_TO_REMOVE, &
     &NDATOMS,LIST_NO_ORDER,NSIA,INDX)
              INTEGER(KIND=4), INTENT(IN) :: NSIA
              INTEGER(KIND=4), INTENT(IN) :: NDATOMS
              REAL(KIND=8), INTENT(OUT) :: ATOMS_TO_REMOVE(NDATOMS)
              REAL(KIND=8), INTENT(IN) :: LIST_NO_ORDER(10*NSIA)
              INTEGER(KIND=4), INTENT(IN) :: INDX(10*NSIA)
            END SUBROUTINE LATTICE_COMPUTE_ATOMS_TO_REMOVE
          END INTERFACE 
        END MODULE LATTICE_COMPUTE_ATOMS_TO_REMOVE__genmod
