        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 16 12:09:22 2010
        MODULE OFFLATTICE_COMPUTE_ATOMS_TO_REMOVE__genmod
          INTERFACE 
            SUBROUTINE OFFLATTICE_COMPUTE_ATOMS_TO_REMOVE(GNDATOMS,     &
     &RXGAOS,RYGAOS,RZGAOS,TEMPRXGAOS,TEMPRYGAOS,TEMPRZGAOS,            &
     &OFFLATTICE_NO_ORDER,INDX,NSIA)
              INTEGER(KIND=4), INTENT(IN) :: NSIA
              INTEGER(KIND=4), INTENT(IN) :: GNDATOMS
              REAL(KIND=8), INTENT(OUT) :: RXGAOS(GNDATOMS)
              REAL(KIND=8), INTENT(OUT) :: RYGAOS(GNDATOMS)
              REAL(KIND=8), INTENT(OUT) :: RZGAOS(GNDATOMS)
              REAL(KIND=8), INTENT(IN) :: TEMPRXGAOS(12*NSIA)
              REAL(KIND=8), INTENT(IN) :: TEMPRYGAOS(12*NSIA)
              REAL(KIND=8), INTENT(IN) :: TEMPRZGAOS(12*NSIA)
              REAL(KIND=8), INTENT(IN) :: OFFLATTICE_NO_ORDER(12*NSIA)
              INTEGER(KIND=4), INTENT(IN) :: INDX(12*NSIA)
            END SUBROUTINE OFFLATTICE_COMPUTE_ATOMS_TO_REMOVE
          END INTERFACE 
        END MODULE OFFLATTICE_COMPUTE_ATOMS_TO_REMOVE__genmod
