        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 16 12:09:22 2010
        MODULE OFFLATTICE_GET_COORDINATES_AND_ORDER__genmod
          INTERFACE 
            SUBROUTINE OFFLATTICE_GET_COORDINATES_AND_ORDER(A0,RXGAOS,  &
     &RYGAOS,RZGAOS,RX,RY,RZ,OFFLATTICE_NO_ORDER,INDX,NSITE,TYPE_OCTA,  &
     &NSIA,NSIZE,GNDATOMS)
              INTEGER(KIND=4), INTENT(IN) :: NSIZE
              INTEGER(KIND=4), INTENT(IN) :: NSIA
              REAL(KIND=8), INTENT(IN) :: A0
              REAL(KIND=8), INTENT(OUT) :: RXGAOS(12*NSIA)
              REAL(KIND=8), INTENT(OUT) :: RYGAOS(12*NSIA)
              REAL(KIND=8), INTENT(OUT) :: RZGAOS(12*NSIA)
              REAL(KIND=8) :: RX(NSIZE)
              REAL(KIND=8) :: RY(NSIZE)
              REAL(KIND=8) :: RZ(NSIZE)
              REAL(KIND=8), INTENT(OUT) :: OFFLATTICE_NO_ORDER(12*NSIA)
              INTEGER(KIND=4), INTENT(OUT) :: INDX(12*NSIA)
              INTEGER(KIND=4), INTENT(IN) :: NSITE(NSIA)
              INTEGER(KIND=4), INTENT(IN) :: TYPE_OCTA(NSIA)
              INTEGER(KIND=4), INTENT(OUT) :: GNDATOMS
            END SUBROUTINE OFFLATTICE_GET_COORDINATES_AND_ORDER
          END INTERFACE 
        END MODULE OFFLATTICE_GET_COORDINATES_AND_ORDER__genmod
