        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 16 12:09:22 2010
        MODULE PRINT_SUFFIX_BS__genmod
          INTERFACE 
            SUBROUTINE PRINT_SUFFIX_BS(IUNIT)
              INTEGER(KIND=4), INTENT(IN) :: IUNIT
            END SUBROUTINE PRINT_SUFFIX_BS
          END INTERFACE 
        END MODULE PRINT_SUFFIX_BS__genmod
