        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 16 12:09:22 2010
        MODULE READ_NTEMP__genmod
          INTERFACE 
            SUBROUTINE READ_NTEMP(NTEMP)
              INTEGER(KIND=4) :: NTEMP
            END SUBROUTINE READ_NTEMP
          END INTERFACE 
        END MODULE READ_NTEMP__genmod
