        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 16 12:09:22 2010
        MODULE ROTATION_MATRIX_Z__genmod
          INTERFACE 
            SUBROUTINE ROTATION_MATRIX_Z(TETA,MATRIX_IN,MATRIX_OUT)
              REAL(KIND=8) :: TETA
              REAL(KIND=8) :: MATRIX_IN(3,3)
              REAL(KIND=8) :: MATRIX_OUT(3,3)
            END SUBROUTINE ROTATION_MATRIX_Z
          END INTERFACE 
        END MODULE ROTATION_MATRIX_Z__genmod
