        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:13:02 2013
        MODULE CUT_THE_BCC__genmod
          INTERFACE 
            SUBROUTINE CUT_THE_BCC(RX,RY,RZ,NTEMP,NLOOP,ICENTER,RADIUS)
              INTEGER(KIND=4), INTENT(IN) :: NTEMP
              REAL(KIND=8), INTENT(IN) :: RX(NTEMP)
              REAL(KIND=8), INTENT(IN) :: RY(NTEMP)
              REAL(KIND=8), INTENT(IN) :: RZ(NTEMP)
              INTEGER(KIND=4), INTENT(OUT) :: NLOOP(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: ICENTER
              REAL(KIND=8), INTENT(IN) :: RADIUS
            END SUBROUTINE CUT_THE_BCC
          END INTERFACE 
        END MODULE CUT_THE_BCC__genmod
