        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:13:02 2013
        MODULE FIND_THE_CENTER__genmod
          INTERFACE 
            SUBROUTINE FIND_THE_CENTER(RX,RY,RZ,NTEMP,XMIN,XMAX,YMIN,   &
     &YMAX,ZMIN,ZMAX,ICENTER)
              INTEGER(KIND=4), INTENT(IN) :: NTEMP
              REAL(KIND=8), INTENT(IN) :: RX(NTEMP)
              REAL(KIND=8), INTENT(IN) :: RY(NTEMP)
              REAL(KIND=8), INTENT(IN) :: RZ(NTEMP)
              REAL(KIND=8), INTENT(OUT) :: XMIN
              REAL(KIND=8), INTENT(OUT) :: XMAX
              REAL(KIND=8), INTENT(OUT) :: YMIN
              REAL(KIND=8), INTENT(OUT) :: YMAX
              REAL(KIND=8), INTENT(OUT) :: ZMIN
              REAL(KIND=8), INTENT(OUT) :: ZMAX
              INTEGER(KIND=4), INTENT(OUT) :: ICENTER
            END SUBROUTINE FIND_THE_CENTER
          END INTERFACE 
        END MODULE FIND_THE_CENTER__genmod
