        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:13:02 2013
        MODULE FIND_THE_NCUBE__genmod
          INTERFACE 
            SUBROUTINE FIND_THE_NCUBE(NTEMP,NTCUBE,N1,N2,N3,NCUBE)
              INTEGER(KIND=4), INTENT(IN) :: NTEMP
              INTEGER(KIND=4), INTENT(OUT) :: NTCUBE(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N1(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N2(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N3(NTEMP)
              INTEGER(KIND=4), INTENT(OUT) :: NCUBE
            END SUBROUTINE FIND_THE_NCUBE
          END INTERFACE 
        END MODULE FIND_THE_NCUBE__genmod
