        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:13:02 2013
        MODULE FIND_THE_NOCTO__genmod
          INTERFACE 
            SUBROUTINE FIND_THE_NOCTO(NTEMP,NOCTO,NLOOP,N1,N2,N3,NZ16)
              INTEGER(KIND=4), INTENT(IN) :: NTEMP
              INTEGER(KIND=4), INTENT(OUT) :: NOCTO(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NLOOP(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N1(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N2(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N3(NTEMP)
              INTEGER(KIND=4), INTENT(OUT) :: NZ16
            END SUBROUTINE FIND_THE_NOCTO
          END INTERFACE 
        END MODULE FIND_THE_NOCTO__genmod
