        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:12:12 2013
        MODULE LATTICE_COMPUTE_ATOMS_TO_REMOVE__genmod
          INTERFACE 
            SUBROUTINE LATTICE_COMPUTE_ATOMS_TO_REMOVE(ATOMS_TO_REMOVE, &
     &ATOMS_TO_REMOVE_TYPE,NDATOMS,NLAC_REMOVE,LIST_NO_ORDER,           &
     &NSITE_OCTA_VAC_REMOVE_TYPE,INDX)
              INTEGER(KIND=4), INTENT(IN) :: NLAC_REMOVE
              INTEGER(KIND=4), INTENT(IN) :: NDATOMS
              REAL(KIND=8), INTENT(OUT) :: ATOMS_TO_REMOVE(NDATOMS)
              INTEGER(KIND=4), INTENT(OUT) :: ATOMS_TO_REMOVE_TYPE(     &
     &NDATOMS)
              REAL(KIND=8), INTENT(IN) :: LIST_NO_ORDER(NLAC_REMOVE)
              INTEGER(KIND=4), INTENT(IN) :: NSITE_OCTA_VAC_REMOVE_TYPE(&
     &NLAC_REMOVE)
              INTEGER(KIND=4), INTENT(IN) :: INDX(NLAC_REMOVE)
            END SUBROUTINE LATTICE_COMPUTE_ATOMS_TO_REMOVE
          END INTERFACE 
        END MODULE LATTICE_COMPUTE_ATOMS_TO_REMOVE__genmod
