        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:12:12 2013
        MODULE LATTICE_COMPUTE_DIFFERENT_REMOVEATOMS__genmod
          INTERFACE 
            SUBROUTINE LATTICE_COMPUTE_DIFFERENT_REMOVEATOMS(NSIA,      &
     &NLAC_REMOVE,NSITE_OCTA_VAC_REMOVE,INDX,LIST_NO_ORDER,NDATOMS)
              INTEGER(KIND=4), INTENT(IN) :: NLAC_REMOVE
              INTEGER(KIND=4), INTENT(IN) :: NSIA
              INTEGER(KIND=4) :: NSITE_OCTA_VAC_REMOVE(10*NSIA)
              INTEGER(KIND=4), INTENT(OUT) :: INDX(NLAC_REMOVE)
              REAL(KIND=8), INTENT(OUT) :: LIST_NO_ORDER(NLAC_REMOVE)
              INTEGER(KIND=4), INTENT(OUT) :: NDATOMS
            END SUBROUTINE LATTICE_COMPUTE_DIFFERENT_REMOVEATOMS
          END INTERFACE 
        END MODULE LATTICE_COMPUTE_DIFFERENT_REMOVEATOMS__genmod
