        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:09:43 2013
        MODULE PRINT_SUFFIX_BS__genmod
          INTERFACE 
            SUBROUTINE PRINT_SUFFIX_BS(IUNIT)
              INTEGER(KIND=4), INTENT(IN) :: IUNIT
            END SUBROUTINE PRINT_SUFFIX_BS
          END INTERFACE 
        END MODULE PRINT_SUFFIX_BS__genmod
