        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:09:44 2013
        MODULE READ_NTEMP__genmod
          INTERFACE 
            SUBROUTINE READ_NTEMP(NTEMP)
              INTEGER(KIND=4) :: NTEMP
            END SUBROUTINE READ_NTEMP
          END INTERFACE 
        END MODULE READ_NTEMP__genmod
