        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:12:12 2013
        MODULE READ_CONFIG_SIA_OCTA__genmod
          INTERFACE 
            SUBROUTINE READ_CONFIG_SIA_OCTA(NSIA,TYPE_OCTA,NS1,NS2,NS3, &
     &N1MAX,N2MAX,N3MAX)
              INTEGER(KIND=4) :: NSIA
              INTEGER(KIND=4) :: TYPE_OCTA(NSIA)
              INTEGER(KIND=4) :: NS1(NSIA)
              INTEGER(KIND=4) :: NS2(NSIA)
              INTEGER(KIND=4) :: NS3(NSIA)
              INTEGER(KIND=4) :: N1MAX
              INTEGER(KIND=4) :: N2MAX
              INTEGER(KIND=4) :: N3MAX
            END SUBROUTINE READ_CONFIG_SIA_OCTA
          END INTERFACE 
        END MODULE READ_CONFIG_SIA_OCTA__genmod
