        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:09:43 2013
        MODULE REFLEXION__genmod
          INTERFACE 
            SUBROUTINE REFLEXION(TYPE_R,N_REFLEXION,MATRIX_IN,MATRIX_OUT&
     &)
              INTEGER(KIND=4), INTENT(IN) :: TYPE_R
              INTEGER(KIND=4), INTENT(IN) :: N_REFLEXION
              REAL(KIND=8), INTENT(IN) :: MATRIX_IN(3,3)
              REAL(KIND=8), INTENT(OUT) :: MATRIX_OUT(3,3)
            END SUBROUTINE REFLEXION
          END INTERFACE 
        END MODULE REFLEXION__genmod
