        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:09:43 2013
        MODULE ROTATION_VECTOR_Z__genmod
          INTERFACE 
            SUBROUTINE ROTATION_VECTOR_Z(TETA,VECTOR_IN,VECTOR_OUT)
              REAL(KIND=8) :: TETA
              REAL(KIND=8) :: VECTOR_IN(3)
              REAL(KIND=8) :: VECTOR_OUT(3)
            END SUBROUTINE ROTATION_VECTOR_Z
          END INTERFACE 
        END MODULE ROTATION_VECTOR_Z__genmod
