        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:13:02 2013
        MODULE WRITE_NO00INP__genmod
          INTERFACE 
            SUBROUTINE WRITE_NO00INP(NTEMP,N1,N2,N3,NLOOP,NOCTO,NZ16)
              INTEGER(KIND=4), INTENT(IN) :: NTEMP
              INTEGER(KIND=4), INTENT(IN) :: N1(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N2(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N3(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NLOOP(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NOCTO(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NZ16
            END SUBROUTINE WRITE_NO00INP
          END INTERFACE 
        END MODULE WRITE_NO00INP__genmod
