        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:13:02 2013
        MODULE WRITE_XYZ_NOCTO__genmod
          INTERFACE 
            SUBROUTINE WRITE_XYZ_NOCTO(NTEMP,RX,RY,RZ,NLOOP,NOCTO,NTCUBE&
     &,NZ16,NCUBE)
              INTEGER(KIND=4), INTENT(IN) :: NTEMP
              REAL(KIND=8), INTENT(IN) :: RX(NTEMP)
              REAL(KIND=8), INTENT(IN) :: RY(NTEMP)
              REAL(KIND=8), INTENT(IN) :: RZ(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NLOOP(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NOCTO(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NTCUBE(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NZ16
              INTEGER(KIND=4), INTENT(IN) :: NCUBE
            END SUBROUTINE WRITE_XYZ_NOCTO
          END INTERFACE 
        END MODULE WRITE_XYZ_NOCTO__genmod
