        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:13:02 2013
        MODULE WRITE_NO00XYZ__genmod
          INTERFACE 
            SUBROUTINE WRITE_NO00XYZ(NTEMP,RX,RY,RZ,N1,N2,N3,NLOOP,NOCTO&
     &,NZ16,XMAX,YMAX,ZMAX,XMIN,YMIN,ZMIN)
              INTEGER(KIND=4), INTENT(IN) :: NTEMP
              REAL(KIND=8), INTENT(IN) :: RX(NTEMP)
              REAL(KIND=8), INTENT(IN) :: RY(NTEMP)
              REAL(KIND=8), INTENT(IN) :: RZ(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N1(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N2(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N3(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NLOOP(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NOCTO(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NZ16
              REAL(KIND=8), INTENT(OUT) :: XMAX
              REAL(KIND=8), INTENT(OUT) :: YMAX
              REAL(KIND=8), INTENT(OUT) :: ZMAX
              REAL(KIND=8), INTENT(OUT) :: XMIN
              REAL(KIND=8), INTENT(OUT) :: YMIN
              REAL(KIND=8), INTENT(OUT) :: ZMIN
            END SUBROUTINE WRITE_NO00XYZ
          END INTERFACE 
        END MODULE WRITE_NO00XYZ__genmod
