        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 18 15:13:02 2013
        MODULE WRITE_N00_AND_BEYONDXYZ__genmod
          INTERFACE 
            SUBROUTINE WRITE_N00_AND_BEYONDXYZ(NTEMP,RX,RY,RZ,N1,N2,N3, &
     &NLOOP,NOCTO,NLOOPC,NOCTOC,NTCUBE,NZ16,NZ16C,NCUBE,XMAXC,YMAXC,    &
     &ZMAXC,XMINC,YMINC,ZMINC,A0)
              INTEGER(KIND=4), INTENT(IN) :: NTEMP
              REAL(KIND=8), INTENT(IN) :: RX(NTEMP)
              REAL(KIND=8), INTENT(IN) :: RY(NTEMP)
              REAL(KIND=8), INTENT(IN) :: RZ(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N1(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N2(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: N3(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NLOOP(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NOCTO(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NLOOPC(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NOCTOC(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NTCUBE(NTEMP)
              INTEGER(KIND=4), INTENT(IN) :: NZ16
              INTEGER(KIND=4), INTENT(IN) :: NZ16C
              INTEGER(KIND=4), INTENT(IN) :: NCUBE
              REAL(KIND=8), INTENT(INOUT) :: XMAXC
              REAL(KIND=8), INTENT(INOUT) :: YMAXC
              REAL(KIND=8), INTENT(INOUT) :: ZMAXC
              REAL(KIND=8), INTENT(INOUT) :: XMINC
              REAL(KIND=8), INTENT(INOUT) :: YMINC
              REAL(KIND=8), INTENT(INOUT) :: ZMINC
              REAL(KIND=8), INTENT(IN) :: A0
            END SUBROUTINE WRITE_N00_AND_BEYONDXYZ
          END INTERFACE 
        END MODULE WRITE_N00_AND_BEYONDXYZ__genmod
