#!/bin/bash
#MSUB -q ivybridge 
##MSUB -q standard 
#MSUB -r NNAMEE
#MSUB -n 800    
#MSUB -T 50000  
#MSUB -o file.o%J 
#MSUB -e file.e%J  
#MSUB -A den 
##MSUB -A genden 

suff=SSUFF
name=NNAMEE
export OMPI_MCA_coll="^ghc"
module load vasp

export nprocs=${BRIDGE_MSUB_NPROC}
export OMP_NUM_THREADS=1
#ort EXE=${WORKDIR}/VaspC/bin/vasp_t.x
export EXE=/ccc/products/vasp-5.4.1/default/bin/vasp_std
export VASP_PSEUDO=/ccc/work/cont002/den/marinica/Polar_vac/VASP/POTCAR.vasp
export VASP_TMPDIR=${SCRATCHDIR}/AlSia/${suff}/${name}

rm -rf   ${VASP_TMPDIR}
mkdir -p ${VASP_TMPDIR}
cd ${VASP_TMPDIR}

pwd



SUBMISSION=${BRIDGE_MSUB_PWD}
cp ${SUBMISSION}/INCAR   INCAR
cp ${VASP_PSEUDO}         POTCAR
cp ${SUBMISSION}/POSCAR   POSCAR
cp /ccc/work/cont002/den/marinica/Polar_vac/VASP/KPOINTS.vasp                  KPOINTS

pwd
outputfile=${BRIDGE_MSUB_PWD}/w${suff}.out
ulimit -c unlimited
#mpirun.bullxmpi -mca coll ^tuned -np $nprocs ${EXE} -ndiag ${northo}  -npool ${pools} -ntg ${ntaskg} < input |tee $outputfile
mpirun  -np $nprocs ${EXE}   |tee $outputfile

cp OUTCAR  ${BRIDGE_MSUB_PWD}/OUTCAR
cp CONTCAR ${BRIDGE_MSUB_PWD}/CONTCAR
cp OSZICAR ${BRIDGE_MSUB_PWD}/
